# Makefile.common - shared code between MesaLib ports.

MESAVERSION=	26.0.0

MASTER_SITES=	https://mesa.freedesktop.org/archive/

DISTFILES=	mesa-${MESAVERSION}${EXTRACT_SUFX}

PATCH_SITES=	https://gitlab.freedesktop.org/mesa/mesa/-/commit/

MAINTAINER=	4983626+dianeasaur@users.noreply.github.com # x11@FreeBSD.org

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/docs/license.rst

COMPONENT=	${PORTNAME:tl:C/^lib//:C/mesa-//}

BUILD_DEPENDS+=	${PYTHON_PKGNAMEPREFIX}mako>0:textproc/py-mako@${PY_FLAVOR} \
		${PYTHON_PKGNAMEPREFIX}packaging>0:devel/py-packaging@${PY_FLAVOR}
.if ${COMPONENT} != clover
.if ${PORT_OPTIONS:MX11}
USES+=	xorg
.endif
.endif

LIB_DEPENDS+=	libdrm.so:graphics/libdrm
.if ${COMPONENT} != osmesa
LIB_DEPENDS+=	libexpat.so:textproc/expat2
.endif

.if ${PORT_OPTIONS:MIRIS}
BUILD_DEPENDS+=	libclc-${LLVM_PORT:T}>0:devel/libclc@${LLVM_PORT:T} \
			spirv-tools>0:graphics/spirv-tools \
			spirv-llvm-translator-${LLVM_PORT:T}>0:devel/spirv-llvm-translator@${LLVM_PORT:T}
RUN_DEPENDS+=	spirv-tools>0:graphics/spirv-tools \
			spirv-llvm-translator-${LLVM_PORT:T}>0:devel/spirv-llvm-translator@${LLVM_PORT:T}
CONFIGURE_ENV+=	PKG_CONFIG_PATH="${LLVM_PREFIX}/libdata/pkgconfig"
.endif

.if ${PORT_OPTIONS:MANV}
BUILD_DEPENDS+=      glslangValidator:graphics/glslang \
        libclc-${LLVM_PORT:T}>0:devel/libclc@${LLVM_PORT:T} \
        spirv-llvm-translator-${LLVM_PORT:T}>0:devel/spirv-llvm-translator@${LLVM_PORT:T} \
        spirv-tools>0:graphics/spirv-tools
LIB_DEPENDS+=       libxcb-keysyms.so.1:x11/xcb-util-keysyms \
        libdisplay-info.so.3:sysutils/libdisplay-info \
        libudev.so.0:devel/libudev-devd
CONFIGURE_ENV+=     PKG_CONFIG_PATH="${LLVM_PREFIX}/libdata/pkgconfig"
.endif

USES+=		compiler:c++11-lib bison meson pathfix pkgconfig \
		python:build shebangfix tar:xz

# only have one port to check with portscout.
.if ${PORTNAME} != mesa-dri
PORTSCOUT=	ignore:1
.endif

MASTERDIR=	${.CURDIR:H:H}/graphics/mesa-dri
PATCHDIR=	${MASTERDIR}/files
WRKSRC=		${WRKDIR}/mesa-${MESAVERSION}
DESCR=		${.CURDIR}/pkg-descr
PLIST=		${.CURDIR}/pkg-plist
PKGHELP=	${.CURDIR}/pkg-help
PKGINSTALL=	${.CURDIR}/pkg-install
PKGDEINSTALL=	${.CURDIR}/pkg-deinstall

.include <bsd.port.pre.mk>

BINARY_ALIAS+=	python3=${PYTHON_VERSION}

CONFIGURE_ENV+=	LLVM_CONFIG=${LLVM_CONFIG}

# Some symbols in mesa's linker version scripts are not always defined,
# depending on configuration options. Suppress errors with lld >= 17 due to
# these undefined symbols.
LDFLAGS+=	-Wl,--undefined-version

LDFLAGS+=	-Wl,-rpath=${LOCALBASE}/llvm${LLVM_VERSION}/lib
MESON_ARGS+=	-Dllvm=enabled \
		-Dlibunwind=disabled
